<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>ThirdPerson.Startup.Server</AssemblyName>
    <RootNamespace>ThirdPerson.Startup.Server</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishAot>false</PublishAot>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Host\ThirdPerson.Server.Host.csproj" />
    <ProjectReference Include="..\Entity\ThirdPerson.Server.StartupAuth.Entity.csproj" />
    <ProjectReference Include="..\Hotfix\ThirdPerson.Server.StartupAuth.Hotfix.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\Shared\Host\NLog.config" Link="NLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <None Update="Fantasy.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
