<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>ThirdPerson.Development.Gm.Contracts</AssemblyName>
    <RootNamespace>ThirdPerson.Development.Gm</RootNamespace>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../../Shared/UnityPackages/com.thirdperson.tooling-contracts/Editor/Gm/**/*.cs" />
  </ItemGroup>
</Project>
