<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Shared/Development/Gm.Client/ThirdPerson.Development.Gm.Client.csproj" />
    <ProjectReference Include="../../Shared/Development/RollbackGm.Server/ThirdPerson.Development.RollbackGm.Server.csproj" />
  </ItemGroup>
</Project>
