<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>ThirdPerson.Server.Host</AssemblyName>
    <RootNamespace>ThirdPerson.Server.Host</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsDirectFantasyNetReference>false</IsDirectFantasyNetReference>
    <FantasyConfigAutoDiscoveryEnabled>false</FantasyConfigAutoDiscoveryEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NLog" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fantasy-Net" Version="2026.0.1020" />
  </ItemGroup>
  <ItemGroup>
    <None Update="NLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
