<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>ThirdPerson.Server.DotRecastAuthority.Entity</AssemblyName>
    <RootNamespace>Fantasy</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Gate\Entity\ThirdPerson.Server.Gate.Entity.csproj" />
    <ProjectReference Include="..\..\..\..\..\Tools\ThirdPersonSimulation.Portable\ThirdPersonSimulation.Core\ThirdPersonSimulation.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\Tools\ThirdPersonSimulation.Portable\ThirdPersonSimulation.Float32\ThirdPersonSimulation.Float32.csproj" />
    <ProjectReference Include="..\..\..\..\..\Tools\ThirdPersonSimulation.Portable\ThirdPersonSimulation.ServerAuthoritative\ThirdPersonSimulation.ServerAuthoritative.csproj" />
    <ProjectReference Include="..\..\..\..\..\Tools\ThirdPersonSimulation.Portable\ThirdPersonSimulation.ServerAuthoritative.Transport\ThirdPersonSimulation.ServerAuthoritative.Transport.csproj" />
    <ProjectReference Include="..\..\..\..\..\Tools\ThirdPersonSimulation.Portable\ThirdPersonSimulation.DotRecast\ThirdPersonSimulation.DotRecast.csproj" />
    <ProjectReference Include="..\..\..\..\..\Tools\ThirdPersonSimulation.Portable\ThirdPersonSimulation.DotRecastAuthority\ThirdPersonSimulation.DotRecastAuthority.csproj" />
  </ItemGroup>
</Project>
