namespace Fantasy;

public static class ServerAuthoritativeRegistrationMapper
{
    public static ServerAuthoritativeAuthorityHostRegistration Build(
        IServerAuthoritativeAuthorityHostEndpoint endpoint,
        string hostProductId,
        string hostId,
        ServerAuthoritativeAuthorityHostRouteKind routeKind,
        string roomId,
        uint modelProtocolVersion,
        string modelId,
        string modelConfigurationHash,
        string endpointId,
        string programId,
        string programHash,
        string layoutHash,
        string operationSetId,
        string operationSetVersion,
        string authorityPipelineId,
        string authorityPipelineHash,
        string predictionPipelineId,
        string predictionPipelineHash,
        string backendId,
        uint tickRate,
        string solverId,
        string solverVersion,
        ulong solverCapabilities,
        ulong solverFeatures,
        string worldId,
        string mapId,
        string worldRevision,
        string worldConfigurationHash,
        string navigationSurfaceArtifactHash,
        string queryProfileHash,
        string dataHost,
        uint dataPort) => new()
    {
        RoomId = roomId,
        HostProductId = hostProductId,
        HostId = hostId,
        RouteKind = routeKind,
        Endpoint = endpoint,
        EndpointId = endpointId,
        ModelProtocolVersion = modelProtocolVersion,
        ModelId = modelId,
        ModelConfigurationHash = modelConfigurationHash,
        ProgramId = programId,
        ProgramHash = programHash,
        LayoutHash = layoutHash,
        OperationSetId = operationSetId,
        OperationSetVersion = operationSetVersion,
        AuthorityPipelineId = authorityPipelineId,
        AuthorityPipelineHash = authorityPipelineHash,
        PredictionPipelineId = predictionPipelineId,
        PredictionPipelineHash = predictionPipelineHash,
        BackendId = backendId,
        TickRate = tickRate,
        SolverId = solverId,
        SolverVersion = solverVersion,
        SolverCapabilities = solverCapabilities,
        SolverFeatures = solverFeatures,
        WorldId = worldId,
        MapId = mapId,
        WorldRevision = worldRevision,
        WorldConfigurationHash = worldConfigurationHash,
        NavigationSurfaceArtifactHash = navigationSurfaceArtifactHash,
        QueryProfileHash = queryProfileHash,
        DataHost = dataHost,
        DataPort = dataPort
    };
}
